package com.moneymanager.app.ui.categories

import org.junit.Assert.assertNotEquals
import org.junit.Test

class CategoryIconCoverageTest {
    @Test
    fun everyImportedCategoryHasASemanticCustomGlyph() {
        val names = listOf(
            "A/c to A/c",
            "Beauty/Fitness",
            "Bike",
            "Bills/Utilities",
            "Books",
            "Breakfast",
            "Business",
            "Cable",
            "Canara Bank",
            "Car",
            "Cash Forward",
            "Cash Spend",
            "Cash Withdrawal",
            "CC Bill Payment",
            "Cheque",
            "Clothes",
            "Coffee",
            "Cookies",
            "Cooking Oil",
            "Courier",
            "Credit Card",
            "Debit Card",
            "Dining",
            "Dinner",
            "Donation",
            "Drinks",
            "Education",
            "Electronics",
            "EMI",
            "Entertainment",
            "Family Function",
            "Fast Food",
            "Finance",
            "Flowers",
            "Food & Drinks",
            "Fruits",
            "Gas",
            "Gifts",
            "Gold",
            "Grocery",
            "Hotel",
            "Household",
            "Ice-cream",
            "IMPS",
            "Insurance",
            "Interest",
            "Investment Income",
            "Investments",
            "Jewellery",
            "Kids",
            "Loan",
            "Lunch",
            "Maintenance",
            "Medical",
            "Miscellaneous",
            "Mobile",
            "Mutual Funds",
            "NetBanking",
            "Office",
            "Online Transfer",
            "Others",
            "Pastries",
            "Personal Care",
            "Post Office",
            "Prepaid Wallet",
            "Printing/Scanning",
            "Provident Fund",
            "Refund",
            "Rent/Mortgage",
            "Reward",
            "Salary",
            "Salon",
            "Savings",
            "Selling",
            "Shoes",
            "Shopping",
            "Stationery",
            "STOCKS BUYING",
            "STOCKS SELLING",
            "Sweet and Snacks Backery",
            "Tax",
            "Taxi",
            "Temple Visit",
            "Toys",
            "Transport",
            "Travel",
            "Unknown",
            "UPI",
            "vegetables",
            "Wallet Recharge",
            "Wi-Fi"
        )
        names.forEach { name ->
            val style = oneUiCategoryStyle(name, name.lowercase().replace(" ", "_"))
            assertNotEquals("$name must not fall back to the generic custom glyph", CategoryIconKind.Custom, style.kind)
        }
    }
}
